#pragma once

#include <string>
#include <unordered_map>

#include "openpilot/cereal/gen/cpp/log.capnp.h"

inline static std::unordered_map<std::string, ParamKeyAttributes> keys = {
    {"AccessToken", {CLEAR_ON_MANAGER_START | DONT_LOG, STRING}},
    {"AdbEnabled", {PERSISTENT, BOOL}},
    {"AlwaysOnDM", {PERSISTENT, BOOL}},
    {"ApiCache_Device", {PERSISTENT, STRING}},
    {"ApiCache_FirehoseStats", {PERSISTENT, JSON}},
    {"AssistNowToken", {PERSISTENT, STRING}},
    {"AthenadPid", {PERSISTENT, INT}},
    {"AthenadUploadQueue", {PERSISTENT, JSON}},
    {"AthenadRecentlyViewedRoutes", {PERSISTENT, STRING}},
    {"BootCount", {PERSISTENT, INT}},
    {"CalibrationParams", {PERSISTENT, BYTES}},
    {"CameraDebugExpGain", {CLEAR_ON_MANAGER_START, STRING}},
    {"CameraDebugExpTime", {CLEAR_ON_MANAGER_START, STRING}},
    {"CarBatteryCapacity", {PERSISTENT, INT}},
    {"CarParams", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BYTES}},
    {"CarParamsCache", {CLEAR_ON_MANAGER_START, BYTES}},
    {"CarParamsPersistent", {PERSISTENT, BYTES}},
    {"CarParamsPrevRoute", {PERSISTENT, BYTES}},
    {"CompletedTrainingVersion", {PERSISTENT, STRING, "0"}},
    {"ControlsReady", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"CurrentBootlog", {PERSISTENT, STRING}},
    {"CurrentRoute", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, STRING}},
    {"DisableLogging", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"DisablePowerDown", {PERSISTENT, BOOL}},
    {"DisableUpdates", {PERSISTENT, BOOL}},
    {"DisengageOnAccelerator", {PERSISTENT, BOOL, "0"}},
    {"DongleId", {PERSISTENT, STRING}},
    {"DoReboot", {CLEAR_ON_MANAGER_START, BOOL}},
    {"DoShutdown", {CLEAR_ON_MANAGER_START, BOOL}},
    {"DoUninstall", {CLEAR_ON_MANAGER_START, BOOL}},
    {"DriverTooDistracted", {CLEAR_ON_MANAGER_START | CLEAR_ON_IGNITION_ON, BOOL}},
    {"DriverLockoutCount", {CLEAR_ON_MANAGER_START | CLEAR_ON_IGNITION_ON, INT, "0"}},
    {"AlphaLongitudinalEnabled", {PERSISTENT | DEVELOPMENT_ONLY, BOOL}},
    {"ExperimentalMode", {PERSISTENT, BOOL}},
    {"ExperimentalModeConfirmed", {PERSISTENT, BOOL}},
    {"FirmwareQueryDone", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"ForcePowerDown", {PERSISTENT, BOOL}},
    {"GitBranch", {PERSISTENT, STRING}},
    {"GitCommit", {PERSISTENT, STRING}},
    {"GitCommitDate", {PERSISTENT, STRING}},
    {"GitDiff", {PERSISTENT, STRING}},
    {"GithubSshKeys", {PERSISTENT, STRING}},
    {"GithubUsername", {PERSISTENT, STRING}},
    {"GitRemote", {PERSISTENT, STRING}},
    {"GsmApn", {PERSISTENT, STRING}},
    {"GsmMetered", {PERSISTENT, BOOL, "1"}},
    {"GsmRoaming", {PERSISTENT, BOOL}},
    {"HardwareSerial", {PERSISTENT, STRING}},
    {"HasAcceptedTerms", {PERSISTENT, STRING, "0"}},
    {"InstallDate", {PERSISTENT, TIME}},
    {"IsDriverViewEnabled", {CLEAR_ON_MANAGER_START, BOOL}},
    {"IsEngaged", {PERSISTENT, BOOL}},
    {"IsLdwEnabled", {PERSISTENT, BOOL}},
    {"IsLiveStreaming", {CLEAR_ON_MANAGER_START, BOOL}},
    {"IsMetric", {PERSISTENT, BOOL, "1"}},
    {"IsOffroad", {CLEAR_ON_MANAGER_START, BOOL}},
    {"IsRhdDetected", {PERSISTENT, BOOL}},
    {"IsReleaseBranch", {CLEAR_ON_MANAGER_START, BOOL}},
    {"IsTestedBranch", {CLEAR_ON_MANAGER_START, BOOL}},
    {"JoystickDebugMode", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"LanguageSetting", {PERSISTENT, STRING, "en"}},
    {"LastAthenaPingTime", {CLEAR_ON_MANAGER_START, INT}},
    {"LastGPSPosition", {PERSISTENT, STRING}},
    {"LastManagerExitReason", {CLEAR_ON_MANAGER_START, STRING}},
    {"LastOffroadStatusPacket", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, JSON}},
    {"LastAgnosPowerMonitorShutdown", {CLEAR_ON_MANAGER_START, STRING}},
    {"LastPowerDropDetected", {CLEAR_ON_MANAGER_START, STRING}},
    {"LastUpdateException", {CLEAR_ON_MANAGER_START, STRING}},
    {"LastUpdateRouteCount", {PERSISTENT, INT, "0"}},
    {"LastUpdateTime", {PERSISTENT, TIME}},
    {"LastUpdateUptimeOnroad", {PERSISTENT, FLOAT, "0.0"}},
    // TODO: rename the Live* learner cache keys to match their Cereal services, with migration for persisted values.
    {"LiveDelay", {PERSISTENT, BYTES}},
    {"LiveParametersV2", {PERSISTENT, BYTES}},
    {"LivestreamEncoderBitrate", {CLEAR_ON_MANAGER_START | DONT_LOG, INT}},
    {"LivestreamRequestKeyframe", {CLEAR_ON_MANAGER_START | DONT_LOG, BOOL}},
    {"LiveTorqueParameters", {PERSISTENT | DONT_LOG, BYTES}},
    {"LocationFilterInitialState", {PERSISTENT, BYTES}},
    {"LateralManeuverMode", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"LongitudinalManeuverMode", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"LongitudinalPersonality", {PERSISTENT, INT, std::to_string(static_cast<int>(cereal::LongitudinalPersonality::STANDARD))}},
    {"NetworkMetered", {PERSISTENT, BOOL}},
    {"ObdMultiplexingChanged", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"ObdMultiplexingEnabled", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"Offroad_CarUnrecognized", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, JSON}},
    {"Offroad_ConnectivityNeeded", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_ConnectivityNeededPrompt", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_ExcessiveActuation", {PERSISTENT, JSON}},
    {"Offroad_NeosUpdate", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_NoFirmware", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, JSON}},
    {"Offroad_Recalibration", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, JSON}},
    {"Offroad_TemperatureTooHigh", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_UnregisteredHardware", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_UpdateFailed", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_DriverMonitoringUncertain", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, JSON}},
    {"OnroadCycleRequested", {CLEAR_ON_MANAGER_START, BOOL}},
    {"OpenpilotEnabledToggle", {PERSISTENT, BOOL, "1"}},
    {"PandaHeartbeatLost", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"PrimeType", {PERSISTENT, INT}},
    {"RecordAudio", {PERSISTENT, BOOL}},
    {"RecordFront", {PERSISTENT, BOOL}},
    {"RecordFrontLock", {PERSISTENT, BOOL}},  // for the internal fleet
    {"SecOCKey", {PERSISTENT | DONT_LOG, STRING}},
    {"ShowDebugInfo", {PERSISTENT, BOOL}},
    {"RouteCount", {PERSISTENT, INT, "0"}},
    {"SnoozeUpdate", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"SshEnabled", {PERSISTENT, BOOL}},
    {"UbloxAvailable", {PERSISTENT, BOOL}},
    {"UpdateAvailable", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"UpdateFailedCount", {CLEAR_ON_MANAGER_START, INT}},
    {"UpdaterAvailableBranches", {PERSISTENT, STRING}},
    {"UpdaterCurrentDescription", {CLEAR_ON_MANAGER_START, STRING}},
    {"UpdaterCurrentReleaseNotes", {CLEAR_ON_MANAGER_START, BYTES}},
    {"UpdaterFetchAvailable", {CLEAR_ON_MANAGER_START, BOOL}},
    {"UpdaterNewDescription", {CLEAR_ON_MANAGER_START, STRING}},
    {"UpdaterNewReleaseNotes", {CLEAR_ON_MANAGER_START, BYTES}},
    {"UpdaterState", {CLEAR_ON_MANAGER_START, STRING}},
    {"UpdaterTargetBranch", {CLEAR_ON_MANAGER_START, STRING}},
    {"UpdaterLastFetchTime", {PERSISTENT, TIME}},
    {"UptimeOffroad", {PERSISTENT, FLOAT, "0.0"}},
    {"UptimeOnroad", {PERSISTENT, FLOAT, "0.0"}},
    {"UsbGpuActive", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION | CLEAR_ON_IGNITION_ON, BOOL}},
    {"UsbGpuLoading", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION | CLEAR_ON_IGNITION_ON, BOOL}},
    {"Version", {PERSISTENT, STRING}},

    // GM AutoCruise / AutoResume custom parameters
    {"LongitudinalPersonalityMax", {PERSISTENT, INT, "3"}},
    {"NetworkAddress", {CLEAR_ON_MANAGER_START, STRING}},
    {"CarrotNaviDebug", {CLEAR_ON_MANAGER_START, STRING}},
    {"CarrotNaviImage", {CLEAR_ON_MANAGER_START, STRING}},
    {"TrafficLight", {CLEAR_ON_MANAGER_START, STRING}},
    {"CarSelected3", {PERSISTENT, STRING}},
    {"FingerPrints", {PERSISTENT | CLEAR_ON_MANAGER_START, STRING}},
    {"SupportedCars_gm", {PERSISTENT, STRING}},
    {"AutoCruiseControl", {PERSISTENT, INT, "1"}},
    {"AutoGasTokSpeed", {PERSISTENT, INT, "5"}},
    {"AutoEngage", {PERSISTENT, INT, "2"}},
    {"StoppingAccel", {PERSISTENT, INT, "-42"}},
    {"CruiseButtonMode", {PERSISTENT, INT, "2"}},
    {"CruiseSpeedUnit", {PERSISTENT, INT, "5"}},
    {"CruiseSpeedUnitBasic", {PERSISTENT, INT, "5"}},
    {"MyDrivingMode", {PERSISTENT, INT, "3"}},
    // Longitudinal tuning
    {"LongTuningKpV", {PERSISTENT, INT, "0"}},
    {"LongTuningKiV", {PERSISTENT, INT, "0"}},
    {"LongTuningKf", {PERSISTENT, INT, "100"}},
    // Lateral torque tuning
    {"LateralTorqueCustom", {PERSISTENT, BOOL, "1"}},
    {"LateralTorqueAccelFactor", {PERSISTENT, INT, "2100"}},
    {"LateralTorqueFriction", {PERSISTENT, INT, "150"}},
    {"LateralTorqueKpV", {PERSISTENT, INT, "138"}},
    {"LateralTorqueKiV", {PERSISTENT, INT, "25"}},
    {"LateralTorqueKf", {PERSISTENT, INT, "89"}},
    {"LateralTorqueKd", {PERSISTENT, INT, "30"}},


    {"CustomSteerMax", {PERSISTENT, INT, "300"}},
    {"CustomSteerDeltaUp", {PERSISTENT, INT, "14"}},
    {"CustomSteerDeltaDown", {PERSISTENT, INT, "16"}},
    {"CustomSteerDeltaUpLC", {PERSISTENT, INT, "10"}},
    {"CustomSteerDeltaDownLC", {PERSISTENT, INT, "17"}},
    {"CarName", {PERSISTENT, STRING}},
    {"EVTable", {PERSISTENT, BOOL, "1"}},
    {"LongPitch", {PERSISTENT, BOOL, "1"}},
    {"CustomSR", {PERSISTENT, INT, "0"}},
    {"SteerRatioRate", {PERSISTENT, INT, "100"}},
    {"CruiseDelay", {PERSISTENT, INT, "12"}},
    {"ResumeDelay", {PERSISTENT, INT, "6"}},
    {"AccelForce", {PERSISTENT, INT, "950"}},
    // navigation / Carrot Navi
    {"CruiseEcoControl", {PERSISTENT, INT, "0"}},
    {"AutoCurveSpeedLowerLimit", {PERSISTENT, INT, "30"}},
    {"AutoCurveSpeedFactor", {PERSISTENT, INT, "110"}},
    {"AutoTurnControl", {PERSISTENT, INT, "2"}},
    {"AutoTurnControlSpeedTurn", {PERSISTENT, INT, "85"}},
    {"AutoTurnControlTurnEnd", {PERSISTENT, INT, "10"}},
    {"AutoTurnMapChange", {PERSISTENT, INT, "0"}},
    {"AutoNaviCountDownMode", {PERSISTENT, INT, "2"}},
    {"AutoRoadSpeedLimitOffset", {PERSISTENT, INT, "-1"}},
    {"TurnSpeedControlMode", {PERSISTENT, INT, "2"}},
    {"MapTurnSpeedFactor", {PERSISTENT, INT, "90"}},
    {"ModelTurnSpeedFactor", {PERSISTENT, INT, "30"}},
    {"StopDistanceCarrot", {PERSISTENT, INT, "550"}},
    {"JLeadFactor3", {PERSISTENT, INT, "40"}},
    {"MyDrivingModeAuto", {PERSISTENT, INT, "0"}},
    {"TrafficLightDetectMode", {PERSISTENT, INT, "2"}},
    {"CruiseMaxVals0", {PERSISTENT, INT, "160"}},
    {"CruiseMaxVals1", {PERSISTENT, INT, "170"}},
    {"CruiseMaxVals2", {PERSISTENT, INT, "100"}},
    {"CruiseMaxVals3", {PERSISTENT, INT, "70"}},
    {"CruiseMaxVals4", {PERSISTENT, INT, "55"}},
    {"CruiseMaxVals5", {PERSISTENT, INT, "45"}},
    {"CruiseMaxVals6", {PERSISTENT, INT, "30"}},
    {"AChangeCostStarting", {PERSISTENT, INT, "10"}},
    {"TrafficStopDistanceAdjust", {PERSISTENT, INT, "-80"}},
    {"AutoNaviSpeedCtrlEnd", {PERSISTENT, INT, "10"}},
    {"AutoNaviSpeedCtrlMode", {PERSISTENT, INT, "2"}},
    {"AutoNaviSpeedBumpTime", {PERSISTENT, INT, "4"}},
    {"AutoNaviSpeedBumpSpeed", {PERSISTENT, INT, "25"}},
    {"AutoNaviSpeedDecelRate", {PERSISTENT, INT, "100"}},
    {"CarrotException", {CLEAR_ON_MANAGER_START, STRING}},
    {"AutoNaviSpeedSafetyFactor", {PERSISTENT, INT, "95"}},
    {"NavDestination", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, STRING}},
    {"NavDestinationWaypoints", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, STRING}},
};
